# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 648d0cc064770e454b4f76bb2724fa42d80c1ada790912bb1b74875852d649808a7629d77954dc8772f7f9cfa235d7f6a04542d33614e7b32fd0a6de6b640e51

test:
  secret_key_base: 5671654d24d71b148c0b7663ea49cd06f210090612d7226131a40dd8119367786c6d544ac3bbeeeac70192a1996fe21e2ab4fe65a3df54a74112e7013c61cb53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
